data ingest notebook and requirements.txt
GroupAKainos/GroupA_ML pull request #1
Opened 2022-11-25 09:47 UTC by aphawkins1

2022-11-25 10:38 UTC, Andrewwango requested changes
Looks good, got most components! Just some minor changes to make things smoother. One last suggestion: can you change your notebook names to something like: 01-data... and 02-... so it's clear which notebook corresponds to which ticket to which PR! :)

2022-11-25 10:38 UTC, Andrewwango commented on data/data-goes-here.html
> +<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
What is the purpose of all this?

2022-11-25 10:38 UTC, Andrewwango commented on requirements.txt
> +aiohttp==3.8.3
Did you create this with pip freeze? If so, it should look cleaner, like this:
```
beautifulsoup4==4.6.0
bleach==2.0.0
bs4==0.0.1
certifi==2017.7.27.1
chardet==3.0.4
colorama==0.3.9
decorator==4.1.2
entrypoints==0.2.3
html5lib==0.999999999
idna==2.6
ipykernel==4.6.1
```

2022-11-25 10:38 UTC, Andrewwango commented on README.md
> +# GroupA_ML
Please can you remove the content here as it is already in your data ingest notebook - we don't like duplicate text/code :)

2022-11-25 10:38 UTC, Andrewwango commented on Data-ingest-notebook.ipynb
> +    "To enable this notebook to run, please download the following .csv files  from [here](https://huggingface.co/datasets/osyvokon/pavlick-formality-scores/tree/main) and save them in ./data (Hint:
I like the intro - just one thing: for ease of use for future devs, could you code in downloading the files so you don't have to do it manually? `pd.read_csv` should work with urls so it should be easy, then `df.to_csv` to save it locally.

2022-11-25 10:38 UTC, Andrewwango commented on Data-ingest-notebook.ipynb
> +    "### Formal test case:\n",
I really like these: please could you save these to a text file, maybe in a separate folder in `data` called `sanity_check` or something? Then it's really easy to reload this data when you evaluate your model. You can either write to a file using `open(fn, "w")` or use the `%%writefile` magic: https://ipython.readthedocs.io/en/stable/interactive/magics.html#cellmagic-writefile

2022-11-25 14:34 UTC, aphawkins1 commented on Data-ingest-notebook.ipynb
> +    "To enable this notebook to run, please download the following .csv files  from [here](https://huggingface.co/datasets/osyvokon/pavlick-formality-scores/tree/main) and save them in ./data (Hint:
I tried this in the first instance and kept getting SSL errors due to zscaler, so switched to having to manually download the data :(

2022-11-25 14:35 UTC, aphawkins1 commented on data/data-goes-here.html
> +<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
This was just a place holder to ensure the file structure remained. I see you used a .txt file in your repo. I'll use that instead as it's more elegant

2022-11-28 14:19 UTC, hellofadude approved these changes

2022-11-28 14:21 UTC, merged