addied EDA notebook
GroupAKainos/GroupA_ML pull request #2
Opened 2022-11-25 09:50 UTC by aphawkins1

2022-11-25 11:15 UTC, Andrewwango requested changes
Love it. This PR should only bring in changes from ai002 ticket, not another ticket, and I don't want to re-review the changes to existing files from ai001 (README, requirements and data ingestion) Please remove these files from ai001 from this branch. Once ai001 has been merged, then merge main (the changes from ai001) into ai002 (you can do this with `git checkout ai002`, `git merge origin/main`) then reopen a PR.  

In terms of the EDA notebook, again rename it so it's clear it's part of the ai002 ticket. As before, also remove the dataset description from here as it's already in another ticket. 
Also include the code for creating the wordcloud. Finally, why aren't the EDA graphs/charts showing up? (may need a matplotlib inline magic command)

2022-11-28 15:35 UTC, Andrewwango commented on 002-EDA-notebook.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAArwAAAH0CAYAAADfWf7fAAAgAElEQVR4Xuydd3wVRfeHTwgJJARBmkQFRVQEsaCggoUmVbqA9F5C7wTpHQGpoQoCgnReLCAISpOXIqiABSuKKNKbgSSk/j5n+O19k5BkZ9m5m7uT7/6j4c5Oec65u8/Ozu7
Sorry this doesn't seemed to have picked a nice bit of the diff to show - I'm referring to the last cell of markdown in the notebook

2022-11-29 10:37 UTC, aphawkins1 commented on 002-EDA-notebook.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAArwAAAH0CAYAAADfWf7fAAAgAElEQVR4Xuydd3wVRfeHTwgJJARBmkQFRVQEsaCggoUmVbqA9F5C7wTpHQGpoQoCgnReLCAISpOXIqiABSuKKNKbgSSk/j5n+O19k5BkZ9m5m7uT7/6j4c5Oec65u8/Ozu7
Hi Andrew - I have added numerical values to the correlation matrix for sentence length and formality along with some comments :) I have also calculated the average word length to see how that correlates with formality, along with come comments.
Added 2 potential remedies to overcome the class imbalance :)

2022-11-29 10:53 UTC, Andrewwango approved these changes
All good, good luck with training

2022-11-29 11:38 UTC, hellofadude approved these changes

2022-11-29 11:39 UTC, merged